{% set name = "fts3" %}
{% set version = "3.13.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fts3-{{ version }}.tar.gz
  sha256: 9d3f19b35a673df300eedcfde98ba31bdae22ef74be15bd4a17d45f569f9364d

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - m2crypto
    - python >={{ python_min }}
    - requests >=2.20
    - setuptools >=42

test:
  imports:
    - fts3
    - fts3.cli
  commands:
    - pip check
    - fts-rest-ban --help
    - fts-rest-delegate --help
    - fts-rest-delete-submit --help
    - fts-rest-server-status --help
    - fts-rest-transfer-cancel --help
    - fts-rest-transfer-list --help
    - fts-rest-transfer-status --help
    - fts-rest-transfer-submit --help
    - fts-rest-whoami --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://fts.web.cern.ch/
  summary: FTS Python3 CLI and libraries
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://fts3-docs.web.cern.ch/
  dev_url: https://gitlab.cern.ch/fts/fts-rest-flask

extra:
  recipe-maintainers:
    - chrisburr
