{% set name = "fts3" %}
{% set version = "3.13.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fts3-{{ version }}.tar.gz
  sha256: fcc8979b02a5c6689bddca92d153a665dafab76696f65606ab2882f25c653ac9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - m2crypto
    - python >=3.7
    - requests >=2.20
    - setuptools >=42

test:
  imports:
    - fts3
    - fts3.cli
  commands:
    - pip check
    - fts-rest-ban --help
    - fts-rest-delegate --help
    - fts-rest-delete-submit --help
    - fts-rest-server-status --help
    - fts-rest-transfer-cancel --help
    - fts-rest-transfer-list --help
    - fts-rest-transfer-status --help
    - fts-rest-transfer-submit --help
    - fts-rest-whoami --help
  requires:
    - pip

about:
  home: https://fts.web.cern.ch/
  summary: FTS Python3 CLI and libraries
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://fts3-docs.web.cern.ch/
  dev_url: https://gitlab.cern.ch/fts/fts-rest-flask

extra:
  recipe-maintainers:
    - chrisburr
